//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("GitTools Contributors")]
[assembly: AssemblyProduct("GitReleaseManager")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright 2015 - Present - GitTools Contributors")]
[assembly: NeutralResourcesLanguage("en-GB")]
[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]